apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: grpc-server
  ports:
    - protocol: TCP
      port: 50051  # Replace with the port you want to expose
      targetPort: 50051  # Replace with the port your server listens on
  type: NodePort  # Use ClusterIP if you don't need external access
